apiVersion: v1
kind: Service
metadata:
  name: apache-service
  labels:
    app: apache
spec:
  selector:
    app: apache
  ports:
  - protocol: TCP
    port: 80  # Port na którym serwis Apache będzie dostępny
    targetPort: 80  # Port, na którym działa Apache w kontenerze
  type: ClusterIP  # Może być zmieniony na NodePort lub LoadBalancer, jeśli wymagane
