apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: flux-system
  namespace: production
spec:
  interval: 1m
  url: https://github.com/jkb91jkb91/flux_repo_monorepo
  ref:
    branch: main
