apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: prometheus
  namespace: monitoring
spec:
  interval: 5m
  releaseName: prometheus
  chart:
    spec:
      chart: prometheus
      version: "14.8.0"  # Możesz dostosować wersję w zależności od potrzeb
      sourceRef:
        kind: HelmRepository
        name: bitnami  # Nazwa repozytorium Helm (bitnami)
  values:
    replicaCount: 2  # Możesz dostosować liczbę replik w zależności od potrzeb
    alertmanager:
      enabled: true  # Włączone alertmanager dla Prometheusa
